{% set version = "2.0.9" %}

package:
  name: aesara
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aesara/aesara-{{ version }}.tar.gz
  sha256: 65bcc001a5c2b972dbaef5d552dffe3a9f4dafb29867915975c0cc03121adc2a
  patches:

build:
  number: 0
  entry_points:
    - aesara-cache = bin.aesara_cache:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14
    - pygpu >=0.7.0,<0.8
    - filelock

test:
  imports:
    - aesara
  commands:
    - aesara-cache help

about:
  home: https://github.com/pymc-devs/aesara
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions. Aesara is a fork of the Theano library maintained by the PyMC developers.
  license_file: LICENSE.txt
  dev_url: https://github.com/pymc-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - brandonwillard
